export {default as Login} from './Login'
export {default as Catalog} from './Catalog'
export {default as Analisis_Sintomas} from './Analisis_Sintomas'
export {default as Dashboard} from './Dashboard'
export {default as Comparison} from './Comparison'
export {default as Historial} from './Historial'
